# Generated by Django 5.2.7 on 2025-10-31 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinoSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('growth', models.PositiveIntegerField(default=0)),
                ('health', models.PositiveIntegerField(default=100)),
                ('stamina', models.PositiveIntegerField(default=100)),
                ('hunger', models.PositiveIntegerField(default=100)),
                ('thirst', models.PositiveIntegerField(default=100)),
                ('active_dino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.dino')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='store.playerprofile')),
            ],
        ),
    ]
