# Generated by Django 5.2.7 on 2025-10-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_dinoslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='player_avatars/'),
        ),
    ]
