# Generated by Django 5.2.7 on 2025-10-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_playerprofile_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dino',
            name='is_adult',
        ),
        migrations.AddField(
            model_name='dino',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coinpackage',
            name='coins_amount',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coinpackage',
            name='price_usd',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='dino',
            name='coin_cost',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
